### ISSUE TITLE
Server Crash on waking up: NoSuchMethodError: isBeneficial

### ISSUE THREAD

**Issue by Krutoy242** [Fuzss/let-me-sleep#12]
Server crashing when waking up.

Stacktrace:
```less
java.lang.NoSuchMethodError: net.minecraft.potion.Potion.func_188408_i()Z
    at com.fuzs.letmesleep.helper.ClearPotionsHelper.clearActivePotions(ClearPotionsHelper.java:23)
    at com.fuzs.letmesleep.handler.WakeUpHandler.onPlayerWake(WakeUpHandler.java:84)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2403_WakeUpHandler_onPlayerWake_PlayerWakeUpEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
```

Report: [crash-2021-10-14_16.01.49-server.txt](https://github.com/Fuzss/letmesleep/files/7346200/crash-2021-10-14_16.01.49-server.txt)

Config: [letmesleep.cfg](https://github.com/Fuzss/letmesleep/files/7346213/letmesleep.txt)

**Comment by Fuzss** [comment]
Fixed in v1.2.3.
